# Generated by Django 3.0.3 on 2020-05-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cases', models.CharField(max_length=264)),
                ('deaths', models.CharField(max_length=264)),
                ('recovered_cases', models.CharField(max_length=264)),
            ],
        ),
    ]
