# Generated by Django 3.0.3 on 2020-05-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cur_date',
            field=models.DateField(auto_now=True),
        ),
    ]
