# Generated by Django 3.0.3 on 2020-05-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_news_cur_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('address', models.CharField(max_length=1032)),
                ('location', models.CharField(max_length=264)),
            ],
        ),
    ]
