# Generated by Django 3.0.3 on 2020-07-25 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donator',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='receiver',
        ),
    ]
