# Generated by Django 3.0.3 on 2020-07-30 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_auto_20200725_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.Profile'),
        ),
    ]
